
data:
  name: mit-bih-15
  path: /workspace/mit-bih-15/stra_preprocess
  lead_num: 1

training:
  batch_size: 64
  epochs: 100
  lr: 1e-4
  patience: 5
  seed: 42
  device: cuda:0

model:
  num_classes: 15
  num_queries: 10
  d_model: 40
  nhead: 8
  num_layers: 6
  num_feature_levels: 3

loss:
  chief_ratio: [68.98, 31.02]
  label_ratio: [73.07, 9.18, 0.91, 7.63, 2.08, 2.90, 0.24, 1.32, 0.86, 0.81, 0.32, 0.25, 0.17, 0.17, 0.10]

metrics:
  conf_threshold: 0.05
  map_iou_thresholds: [0.1, 0.3, 0.5, 0.7]

save:
  dir: outputs/mit-bih-15