data:
  name: shdb-af-5
  path: /workspace/shdb-af-5/stra_preprocess
  lead_num: 2

training:
  batch_size: 64
  epochs: 100
  lr: 1e-4
  patience: 5
  seed: 42
  device: cuda:0

model:
  num_classes: 5
  num_queries: 10
  d_model: 40
  nhead: 8
  num_layers: 6
  num_feature_levels: 3

loss:
  chief_ratio: [78.41, 21.59]
  label_ratio: [78.57, 19.56, 1.54, 0.31, 0.03]

metrics:
  conf_threshold: 0.05
  map_iou_thresholds: [0.1, 0.3, 0.5, 0.7]

save:
  dir: outputs/shdb-af-5